### ISSUE TITLE
Postgres credentials exposed in ConfigMap

### ISSUE THREAD

**Issue by drpsyko101** [makeplane/helm-charts#33]
## Description

https://github.com/makeplane/helm-charts/blob/6258277d8f31c6b70722c7c25a5747b405705ebd/charts/plane-ce/templates/config-secrets/app-env.yaml#L49-L55

This behaviour exposes sensitive Postgres credentials in a ConfigMap, normally visible to a normal user. Both local setup and remote Postgres URL are affected.

## Steps to reproduce

1. [Install plane](https://github.com/makeplane/helm-charts/blob/master/charts/plane-ce/README.md#installing-plane) with the minimal set values
2. `kubectl get configmap plane-app-app-vars -oyaml`

    ```yaml
    data:
      DATABASE_URL: postgresql://plane:plane@postgres:5432/plane
      #                                ^ Visible sensitive information
    ```

## Possible fix

Move `DATABASE_URL` to `app-secrets` secret in `charts/plane-ce/templates/config-secrets/app-env.yaml` since the secret is used similarly to the ConfigMap counterpart.

## System Info

OS: Ubuntu 22.04
Chart Version: plane-ce:1.0.22
