### ISSUE TITLE
Uploads to external MinIO instance

### ISSUE THREAD

**Issue by ioanalytica** [makeplane/helm-charts#86]
We are using this Helm chart for a PoC setup of Plane CE in our Kubernetes cluster (RKE2). 

```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plane-ce
  namespace: plane
spec:
  interval: 24h
  chart:
    spec:
      chart: plane-ce
      version: 1.0.29
      sourceRef:
        kind: HelmRepository
        name: makeplane
        namespace: flux-system
  values:
    planeVersion: stable

    ingress:
      enabled: false
      appHost: "plane.foobar.com"
      minioHost: ""
      rabbitmqHost: "plane-rabbitmq.foobar.com"
      ingressClass: "nginx"
      ingress_annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/force-hsts: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 5m

    redis:
      local_setup: true

    postgres:
      local_setup: false

    rabbitmq:
      local_setup: true

    minio:
      local_setup: false

    web:
      replicas: 1
      assign_cluster_ip: true

    space:
      replicas: 1
      assign_cluster_ip: true

    admin:
      replicas: 1
      assign_cluster_ip: true

    live:
      replicas: 1
      assign_cluster_ip: true

    api:
      replicas: 1
      assign_cluster_ip: true

    worker:
      replicas: 1

    beatworker:
      replicas: 1

    env:
      docstore_bucket: "plane-foobar"
      doc_upload_size_limit: "10485760" # 5MB

    external_secrets:
      rabbitmq_existingSecret: "plane-secret"
      pgdb_existingSecret: "plane-secret"
      doc_store_existingSecret: "plane-secret"
      app_env_existingSecret: "plane-secret"
      live_env_existingSecret: "plane-secret"

```
This is the content of plane-secret (private information obscured):

```
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-secret
  namespace: plane
type: Opaque
stringData:
  DEBUG: "1"
  SECRET_KEY: "<secret>"
  AMQP_URL: "amqp://foobar_adm:foobar_pw@plane-ce-rabbitmq.plane.svc:5672/"
  REDIS_URL: "redis://plane-ce-redis.plane.svc.cluster.local:6379/"
  DATABASE_URL: "postgresql://plane:foobar_pw@plane-db:5432/plane"
  RABBITMQ_DEFAULT_USER: "plane"
  RABBITMQ_DEFAULT_PASS: "foobar_pw"
  USE_MINIO: "1"
  MINIO_ROOT_USER: "foobar_adm"
  MINIO_ROOT_PASSWORD: "foobar_pw"
  AWS_ACCESS_KEY_ID: "<secret>"
  AWS_SECRET_ACCESS_KEY: "<secret>"
  AWS_S3_BUCKET_NAME: "plane-foobar"
  AWS_S3_ENDPOINT_URL: "https://s3.foobar.com"
  AWS_S3_REGION: "eu-west-1"
  FILE_SIZE_LIMIT: "10485760"
  WEB_URL: "https://plane.foobar.com"

```
All pods are coming up. The database is populated - or with subsequents tries - used as left behind.

During startup the API service connects correctly to MinIO and creates or validates the existence of the bucket.

However, it is not possible to upload files. The UI will not report errors. The API service sends a POST with status 200 and a subsequent PATCH request with status 204.

The status is correct since now files are to be found in the bucket afterwards. Calls to the asset URL later result in a HTTP 404.

We have enabled DEBUG which doesn't seem to provide more insight. In other applications we have to specifiy '''path_style: true''' for correct access to a MiniIO bucket. We didn't find any way to specify this for Plane.
